name: Build Sapper and Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    
    - name: Build Sapper
      uses: truewebartisans/actions-sapper@master
    
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: __sapper__/export
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
